eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://192.168.1.252:8761/eureka}
    instance:
      hostname: localhost
